### ISSUE TITLE
align_chromatograph() got an unexpected keyword argument 'ignore_ambig'

### ISSUE THREAD

**Issue by gitstetter** [y9c/cfutils#5]
* Python version: 3.9.7
* Operating System: MacOS

### Description

Calling cfutils.show.show_reference() returns me an error as it sets the variable ignore_ambig: bool.

### Details:

In _cfutils/cfutils/show.show_reference_:

def show_reference(
    ...
    sitepairs = _align_chromatograph_(
        query_record, subject_record, **ignore_ambig=True**
    )
    ...)

In _futils/cfutils/align.align_chromatograph_:

def _align_chromatograph_(
    query_record: SeqRecord, subject_record: SeqRecord   #but no **ignore_ambig** set
    ) -> List[SitePair]: 
...

### Suggested solution
Get rid of **ignore_ambig=True** in cfutils/cfutils/show.show_reference:

def show_reference(
    ...
    sitepairs = _align_chromatograph_(
        query_record, subject_record
    )
    ...)

Really like your work BTW :)

**Comment by gitstetter** [comment]
Traceback:

Traceback (most recent call last):
  File "/Users/XXXX/Projects/YYYY/run copy.py", line 20, in <module>
    show_reference(query_record = control,subject_record = T116_BII_D5, ax= ax2, ref_central =1)
  File "/Users/XXXX/opt/anaconda3/envs/py39/lib/python3.9/site-packages/cfutils/show.py", line 139, in show_reference
    sitepairs = align_chromatograph(
TypeError: align_chromatograph() got an unexpected keyword argument 'ignore_ambig'

**Comment by y9c** [comment]
Thank you very much. I have fixed this in the latest release.
